// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MergePDFs(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function OpenPDF():Promise<string>;

export function PageCount(arg1:string):Promise<number>;

export function RenderPage(arg1:string,arg2:number,arg3:number):Promise<string>;

export function SavePDF():Promise<string>;
