// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenPDF() {
  return window['go']['main']['App']['OpenPDF']();
}

export function PageCount(arg1) {
  return window['go']['main']['App']['PageCount'](arg1);
}

export function RenderPage(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenderPage'](arg1, arg2, arg3);
}
