// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportSplit(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportSplit'](arg1, arg2, arg3);
}

export function MergePDFs(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['MergePDFs'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenPDF() {
  return window['go']['main']['App']['OpenPDF']();
}

export function PageCount(arg1) {
  return window['go']['main']['App']['PageCount'](arg1);
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function RenderPage(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenderPage'](arg1, arg2, arg3);
}

export function SavePDF() {
  return window['go']['main']['App']['SavePDF']();
}
