// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export namespace main {
	export interface OutputFileSpec {
		firstPage: number;
		name: string;
		outDir: string;
	}
}
